import { webConfig } from "./config.js";

const BACKEND_ORDER = ["searxng", "duckduckgo", "tavily", "exa", "firecrawl", "serper"];
const cache = new Map();
const MAX_TOTAL_OUTPUT = 192 * 1024;
const breaker = new Map();
const BREAKER_COOLDOWN_MS = 15 * 60 * 1000;

function config() { return webConfig(); }
function clamp(value, min, max, fallback) { const number = Number(value ?? fallback); return Math.min(Math.max(Number.isFinite(number) ? Math.floor(number) : fallback, min), max); }
function requireKey(name) { const key = config()[`${name}_api_key`]; if (!key) throw new Error(`${name} API key is not configured`); return key; }
function isQuotaError(error) { const status = error?.status; return status === 401 || status === 402 || status === 403 || (status === 400 && /credit|quota|invalid|not enough/i.test(error?.message || "")); }
function tripBreaker(backend, error) { breaker.set(backend, { until: Date.now() + BREAKER_COOLDOWN_MS, reason: String(error?.message || error).slice(0, 160) }); }
function breakerEntry(backend) { const entry = breaker.get(backend); if (!entry) return null; if (Date.now() >= entry.until) { breaker.delete(backend); return null; } return entry; }
export function resetBreaker() { breaker.clear(); }

async function fetchJson(url, init, timeoutMs) {
  const response = await fetch(url, { ...init, signal: AbortSignal.timeout(timeoutMs) });
  if (!response.ok) { let detail = ""; try { detail = (await response.text()).trim().slice(0, 300); } catch {} const error = new Error(`HTTP ${response.status}${detail ? `: ${detail}` : ""}`); error.status = response.status; throw error; }
  const text = await response.text();
  if (!text.trim()) return {};
  try { return JSON.parse(text); } catch { throw new Error(`Expected JSON from ${new URL(url).host}, received non-JSON content.`); }
}

export async function searchSerper(query, max) { const data = await fetchJson("https://google.serper.dev/search", { method: "POST", headers: { "X-API-KEY": requireKey("serper"), "Content-Type": "application/json" }, body: JSON.stringify({ q: query, num: max }) }, 10_000); const results = []; if (data.answerBox) results.push({ title: data.answerBox.title || "Featured Answer", url: data.answerBox.link || "", content: data.answerBox.answer || data.answerBox.snippet || "", engine: "serper/answer" }); if (data.knowledgeGraph) results.push({ title: data.knowledgeGraph.title || "Knowledge Graph", url: data.knowledgeGraph.website || "", content: data.knowledgeGraph.description || "", engine: "serper/knowledge" }); for (const item of data.organic || []) results.push({ title: item.title || "", url: item.link || "", content: item.snippet || "", engine: "serper/google" }); return results; }
export async function searchFirecrawl(query, max) { const data = await fetchJson("https://api.firecrawl.dev/v2/search", { method: "POST", headers: { Authorization: `Bearer ${requireKey("firecrawl")}`, "Content-Type": "application/json" }, body: JSON.stringify({ query, limit: max, sources: ["web"], scrapeOptions: { formats: ["markdown"] } }) }, 15_000); return (data.data?.web || data.data?.news || []).map((item) => ({ title: item.title || "", url: item.url || "", content: item.markdown || item.description || "", engine: `firecrawl/${item.category || "web"}` })); }
export async function searchTavily(query, max) { const data = await fetchJson("https://api.tavily.com/search", { method: "POST", headers: { Authorization: `Bearer ${requireKey("tavily")}`, "Content-Type": "application/json" }, body: JSON.stringify({ query, max_results: max, search_depth: "advanced", topic: "general", include_answer: "advanced" }) }, 15_000); const results = []; if (data.answer) results.push({ title: "AI Summary", url: "", content: data.answer, engine: "tavily/answer" }); for (const item of data.results || []) results.push({ title: item.title || "", url: item.url || "", content: item.content || "", engine: "tavily", publishedDate: item.publishedDate, score: item.score }); return results; }
export async function searchExa(query, max) { const data = await fetchJson("https://api.exa.ai/search", { method: "POST", headers: { "x-api-key": requireKey("exa"), "Content-Type": "application/json" }, body: JSON.stringify({ query, numResults: max, type: "auto", contents: { text: true, highlights: true } }) }, 15_000); return (data.results || []).map((item) => ({ title: item.title || "", url: item.url || "", content: (item.highlights || []).join(" ") || item.text || "", engine: "exa", publishedDate: item.publishedDate, score: item.score })); }
function decodeHtml(value) { return String(value || "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#x27;|&#039;|&apos;/g, "'").replace(/&nbsp;/g, " "); }
export async function searchDuckDuckGo(query, max) { const params = new URLSearchParams({ q: query }); const response = await fetch(`https://html.duckduckgo.com/html/?${params}`, { headers: { "User-Agent": "Mozilla/5.0 (compatible; OpenCode-Optimised-Toolings/1.0)" }, signal: AbortSignal.timeout(12_000) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const html = await response.text(); const results = []; for (const block of html.split(/<div class="[^"]*result__body[^"]*">/).slice(1)) { if (results.length >= max) break; const titleMatch = block.match(/<a[^>]*class="[^"]*result__a[^"]*"[^>]*href="([^"]*)"[^>]*>([\s\S]*?)<\/a>/); if (!titleMatch) continue; let url = titleMatch[1].startsWith("//") ? `https:${titleMatch[1]}` : titleMatch[1]; try { url = new URL(url).searchParams.get("uddg") || url; } catch {} if (/duckduckgo\.com\/y\.js|ad_provider=/.test(titleMatch[1])) continue; const snippetMatch = block.match(/<a[^>]*class="[^"]*result__snippet[^"]*"[^>]*>([\s\S]*?)<\/a>/); results.push({ title: decodeHtml(titleMatch[2].replace(/<[^>]*>/g, "").trim()), url: decodeURIComponent(url), content: decodeHtml(snippetMatch?.[1]?.replace(/<[^>]*>/g, "").trim() || ""), engine: "duckduckgo/html" }); } if (results.length) return results; const fallback = await fetchJson(`https://api.duckduckgo.com/?${new URLSearchParams({ q: query, format: "json", no_html: "1" })}`, { headers: { "User-Agent": "OpenCode-Optimised-Toolings/1.0" } }, 5_000); if (fallback?.AbstractText) results.push({ title: fallback.AbstractTitle || "Summary", url: fallback.AbstractURL || "", content: fallback.AbstractText, engine: "duckduckgo/abstract" }); if (fallback?.Answer) results.push({ title: "Answer", url: fallback.AnswerURL || "", content: fallback.Answer, engine: "duckduckgo/answer" }); return results; }
export async function searchSearxng(query, max) { const ports = config().searxng_ports; const errors = []; for (const port of ports) { try { const data = await fetchJson(`http://127.0.0.1:${port}/search?${new URLSearchParams({ q: query, format: "json" })}`, { headers: { Accept: "application/json" } }, 8_000); return (data.results || []).slice(0, max).map((item) => ({ title: item.title || "", url: item.url || "", content: item.content || "", engine: `searxng/${item.engine || "meta"}`, publishedDate: item.publishedDate })); } catch (error) { errors.push(`${port}: ${error.message}`); } } throw new Error(`local SearXNG unavailable on ports ${ports.join(", ")} (${errors.join("; ")})`); }

const backendFunctions = { serper: searchSerper, firecrawl: searchFirecrawl, tavily: searchTavily, exa: searchExa, duckduckgo: searchDuckDuckGo, searxng: searchSearxng };
function validateBackends(backends) { const selected = backends?.length ? backends : BACKEND_ORDER; const unique = [...new Set(selected.map((item) => String(item).toLowerCase()))]; const invalid = unique.filter((item) => !backendFunctions[item]); if (invalid.length) throw new Error(`Unknown backend(s): ${invalid.join(", ")}`); return unique; }
function canonicalUrl(value) { if (!value) return ""; try { const url = new URL(value); url.hash = ""; for (const key of [...url.searchParams.keys()]) if (/^(utm_|fbclid|gclid)/i.test(key)) url.searchParams.delete(key); return url.toString().replace(/\/$/, ""); } catch { return value.trim().replace(/\/$/, ""); } }
function deduplicate(results) { const seen = new Set(); return results.filter((result) => { const key = canonicalUrl(result.url) || `${result.title}`.trim().toLowerCase(); if (!key || seen.has(key)) return false; seen.add(key); return true; }); }
async function executeQuery(spec, strategy, selectedBackends, ttlMs) { const max = clamp(spec.max_results, 1, 20, 10); const backends = spec.backend ? validateBackends([spec.backend]) : selectedBackends; const cacheKey = JSON.stringify({ query: spec.query.trim(), max, strategy, backends }); const cached = cache.get(cacheKey); if (ttlMs > 0 && cached && Date.now() - cached.createdAt <= ttlMs) return { ...cached.value, cached: true }; const attempts = []; let results = []; if (strategy === "fallback") { for (const backend of backends) { const blocked = breakerEntry(backend); if (blocked) { attempts.push({ backend, status: `skipped (cooldown: ${blocked.reason})` }); continue; } try { const found = await backendFunctions[backend](spec.query, max); attempts.push({ backend, status: found.length ? `ok (${found.length})` : "0 results" }); if (found.length) { results = found.slice(0, max); break; } } catch (error) { if (isQuotaError(error)) tripBreaker(backend, error); attempts.push({ backend, status: `error: ${error.message}` }); } } } else { const active = []; for (const backend of backends) { const blocked = breakerEntry(backend); if (blocked) attempts.push({ backend, status: `skipped (cooldown: ${blocked.reason})` }); else active.push(backend); } const settled = await Promise.allSettled(active.map(async (backend) => ({ backend, results: await backendFunctions[backend](spec.query, max) }))); settled.forEach((item, index) => { const backend = active[index]; if (item.status === "fulfilled") { attempts.push({ backend, status: `ok (${item.value.results.length})` }); results.push(...item.value.results); } else { if (isQuotaError(item.reason)) tripBreaker(backend, item.reason); attempts.push({ backend, status: `error: ${item.reason?.message || item.reason}` }); } }); results = deduplicate(results).slice(0, max); } const value = { query: spec.query, results, attempts, cached: false }; if (ttlMs > 0) cache.set(cacheKey, { createdAt: Date.now(), value }); return value; }
async function mapConcurrent(items, limit, worker) { const results = new Array(items.length); let next = 0; async function consume() { while (true) { const index = next++; if (index >= items.length) return; results[index] = await worker(items[index], index); } } await Promise.all(Array.from({ length: Math.min(limit, items.length) }, consume)); return results; }
function formatBatch(items, strategy) { const successful = items.filter((item) => item.results.length > 0).length; const sections = [`WEB SEARCH RESULT: ${successful === items.length ? "SUCCESS" : successful > 0 ? "PARTIAL SUCCESS" : "FAILED"}`, `WHAT HAPPENED: ${successful} of ${items.length} query(s) returned results. Strategy: ${strategy}.`, `Web search batch: ${items.length} query(s), strategy=${strategy}`]; let bytes = Buffer.byteLength(sections[0]); for (let index = 0; index < items.length; index += 1) { const item = items[index]; let section = `\n=== QUERY ${index + 1}: ${item.query} ===\nOutcome: ${item.results.length ? `RESULTS FOUND (${item.results.length})` : "NO RESULTS"}\nCache: ${item.cached ? "hit; no external backend request was needed" : "miss"}\nBackend attempts:\n${item.attempts.length ? item.attempts.map((attempt) => `  - ${attempt.backend}: ${attempt.status}`).join("\n") : "  - None recorded"}\n\nTechnical: cache: ${item.cached ? "hit" : "miss"}; attempts: ${item.attempts.map((attempt) => `${attempt.backend}=${attempt.status}`).join("; ")}\n`; if (!item.results.length) section += "No results found.\n"; item.results.forEach((result, resultIndex) => { section += `\n${resultIndex + 1}. ${result.title || "Untitled"}\n`; if (result.url) section += `   URL: ${result.url}\n`; section += `   ${String(result.content || "").replace(/\s+/g, " ").slice(0, 800)}\n   Source: ${result.engine || "unknown"}\n`; if (result.publishedDate) section += `   Date: ${result.publishedDate}\n`; if (result.score !== undefined) section += `   Score: ${result.score}\n`; }); const remaining = MAX_TOTAL_OUTPUT - bytes; if (remaining <= 0) { sections.push("\n[WEB BATCH OUTPUT TRUNCATED]"); break; } if (Buffer.byteLength(section) > remaining) section = Buffer.from(section).subarray(0, remaining).toString("utf8") + "\n[WEB BATCH OUTPUT TRUNCATED]"; sections.push(section); bytes += Buffer.byteLength(section); } return sections.join("\n"); }
export async function searchBatch({ queries, strategy = "fallback", backends, maxConcurrency, cacheTtlSeconds }) { const selectedBackends = validateBackends(backends); const ttlMs = clamp(cacheTtlSeconds, 0, 900, 300) * 1000; const concurrency = clamp(maxConcurrency, 1, 6, 4); const items = await mapConcurrent(queries, concurrency, (spec) => executeQuery(spec, strategy, selectedBackends, ttlMs)); return { output: formatBatch(items, strategy), items }; }
