/** @jsxImportSource @opentui/solid */
import { createMemo } from "solid-js"
import { parseCbm } from "../lib/inspect.js"
import { Activity, ContentPane, InspectorCard, InspectorUnavailable, lifecycleOf, OutcomeOverview, PreviewList, resolvedStatus, Section, statusLabel, statusPending } from "./kit.jsx"
function sectionStatus(name) { if (/FAILED|INCONSISTENT/i.test(name)) return "FAILED"; if (/READINESS|FRESHNESS|ARCHITECTURE|SUMMARY|RESULT|SOURCE|CHAIN/i.test(name)) return "SUCCESS"; return "PARTIAL SUCCESS" }
function labelFor(tool) { if (tool === "alonix-index-project") return "Index project"; if (tool === "alonix-index-context") return "Index context"; if (tool === "alonix-index-investigate") return "Index investigate"; return "Index memory" }
export function CbmView(props) {
  const parsed = createMemo(() => parseCbm(props.output ?? ""))
  const lifecycle = createMemo(() => lifecycleOf(props.part))
  const status = createMemo(() => resolvedStatus(props.part, parsed()?.status))
  const sections = createMemo(() => parsed()?.sections?.map((name) => ({ status: sectionStatus(name), label: name.toLowerCase(), meta: "evidence" })) ?? [])
  const summary = createMemo(() => parsed()?.summary ?? String(props.input?.project ?? props.input?.action ?? "indexed evidence"))
  const details = () => parsed() ? <><OutcomeOverview skin={props.skin} status={parsed().status} summary={parsed().summary} facts={[["evidence sections", sections().length], ["strong", sections().filter((item) => item.status === "SUCCESS").length], ["partial", sections().filter((item) => item.status === "PARTIAL SUCCESS").length], ["failed", sections().filter((item) => item.status === "FAILED").length]]} meaning={parsed().status === "SUCCESS" ? ["Indexed evidence is ready; begin with priority source or call-chain sections."] : ["Use successful sections, but do not infer facts from missing or inconsistent evidence."]} /><Section title="Evidence in reading order" skin={props.skin}>{parsed().sectionBodies.map((section, index) => <InspectorCard title={`${index + 1}. ${section.name}`} skin={props.skin} status={sectionStatus(section.name)} meta="indexed evidence"><ContentPane skin={props.skin} lines={section.body.split(/\r?\n/)} limit={sectionStatus(section.name) === "SUCCESS" ? 20 : 14} tail={false} /></InspectorCard>)}</Section>{parsed().sectionBodies.length ? null : <InspectorUnavailable skin={props.skin} message="The CBM response was classified but contained no named evidence sections." />}</> : statusPending(status()) ? <InspectorCard title={`${labelFor(props.tool)} plan`} skin={props.skin} status={status()} pending><text fg={props.skin.muted}>{summary()}</text></InspectorCard> : <InspectorUnavailable skin={props.skin} message={lifecycle().error || `The completed ${props.tool} response did not match its indexed-evidence contract.`} />
  return <Activity label={labelFor(props.tool)} summary={summary().slice(0, 120)} meta={statusLabel(status())} status={status()} pending={statusPending(status())} skin={props.skin} preview={sections().length ? <PreviewList skin={props.skin} items={sections()} /> : null} details={details} />
}
