/** @jsxImportSource @opentui/solid */
import { createMemo } from "solid-js"
import { inputItems, parseDiscovery } from "../lib/inspect.js"
import { Activity, ContentPane, InspectorCard, InspectorUnavailable, lifecycleOf, MetaGrid, OutcomeOverview, PreviewList, resolvedStatus, Section, statusLabel, statusPending } from "./kit.jsx"
export function DiscoveryView(props) {
  const parsed = createMemo(() => parseDiscovery(props.output ?? "", props.tool))
  const lifecycle = createMemo(() => lifecycleOf(props.part))
  const status = createMemo(() => resolvedStatus(props.part, parsed()?.status))
  const items = createMemo(() => parsed()?.items ?? inputItems(props.tool, props.input))
  const isSearch = createMemo(() => props.tool === "alonix-search")
  const label = createMemo(() => isSearch() ? "Search" : "Explore")
  const summary = createMemo(() => parsed() ? parsed().summary : isSearch() ? String(props.input?.file_pattern ?? "files") : String(props.input?.base_dir ?? "project"))
  const details = () => parsed() ? <><OutcomeOverview skin={props.skin} status={parsed().status} summary={parsed().summary} facts={isSearch() ? [["matching items", parsed().metrics?.["Matches found"] ?? items().length], ["files scanned", parsed().metrics?.["Files scanned"]], ["scan complete", parsed().metrics?.["Complete"]]] : [["components", items().length], ["complete", items().filter((item) => item.status === "SUCCESS").length], ["partial", items().filter((item) => item.status === "PARTIAL SUCCESS").length], ["failed", items().filter((item) => item.status === "FAILED").length]]} meaning={parsed().status === "SUCCESS" ? ["Discovery completed within its configured bounds."] : ["At least one discovery boundary was incomplete or failed.", "Missing results remain unknown unless coverage explicitly says complete."]} /><Section title={isSearch() ? "Matches and coverage" : "Exploration components"} skin={props.skin}>{items().map((item, index) => <InspectorCard title={`${index + 1}. ${item.label}`} skin={props.skin} status={item.status} meta={item.meta} />)}</Section><InspectorCard title="Coverage" skin={props.skin} status={parsed().status}><MetaGrid skin={props.skin} entries={Object.entries(parsed().metrics ?? {})} />{parsed().raw ? <ContentPane title="Bounded diagnostics" skin={props.skin} lines={String(parsed().raw).split(/\r?\n/)} limit={12} /> : null}</InspectorCard></> : statusPending(status()) ? <InspectorCard title={`${label()} plan`} skin={props.skin} status={status()} pending><MetaGrid skin={props.skin} entries={[["base directory", props.input?.base_dir], ["file pattern", props.input?.file_pattern], ["query", props.input?.query]]} /></InspectorCard> : <InspectorUnavailable skin={props.skin} message={lifecycle().error || `The completed ${props.tool} response did not match its discovery report contract.`} />
  return <Activity label={label()} summary={summary().slice(0, 120)} meta={statusLabel(status())} status={status()} pending={statusPending(status())} skin={props.skin} preview={items().length ? <PreviewList skin={props.skin} items={items()} /> : null} details={details} />
}
