/** @jsxImportSource @opentui/solid */
import { createMemo } from "solid-js"
import { parseEditResult } from "../lib/edit.js"
import { inputPlanAvailable, pendingPlanSummary, reconcileBatch } from "../lib/batch.js"
import { inputItems } from "../lib/inspect.js"
import { Activity, ContentPane, displayPath, InspectorCard, InspectorDegraded, InspectorUnavailable, lifecycleOf, MetaGrid, OutcomeOverview, PreviewList, resolvedStatus, Section, statusLabel, statusPending } from "./kit.jsx"

function relativeMatch(input, outputPath) { return (input?.actions ?? []).find((action) => outputPath === action.path || outputPath.replaceAll("\\", "/").endsWith(`/${String(action.path).replaceAll("\\", "/")}`)) }
function intendedActions(input, outputPath) { return (input?.actions ?? []).filter((action) => relativeMatch({ actions: [action] }, outputPath)).map((action) => action.operation === "patch" ? `patch · ${action.replacements?.length ?? 0} exact replacement(s)` : `${action.operation} · ${String(action.content ?? "").split(/\r?\n/).length} line(s)`) }
function operationFor(input, outputPath, fallback) { return relativeMatch(input, outputPath)?.operation ?? fallback }
function IntendedDetails({ input, path, skin }) {
  const actions = (input?.actions ?? []).filter((action) => relativeMatch({ actions: [action] }, path))
  return <>{actions.map((action, actionIndex) => <InspectorCard title={`${action.operation} ${actionIndex + 1}`} skin={skin} status="PARTIAL SUCCESS" meta={action.operation === "patch" ? `${action.replacements?.length ?? 0} replacements` : `${String(action.content ?? "").split(/\r?\n/).length} lines`} nested>{action.operation === "patch" ? (action.replacements ?? []).slice(0, 6).map((replacement, index) => <InspectorCard title={`Exact replacement ${index + 1}`} skin={skin} status="PARTIAL SUCCESS" meta={`expected ${replacement.expected_count ?? 1}`} nested><ContentPane title="Before" skin={skin} lines={String(replacement.search ?? "").split(/\r?\n/).map((line) => `- ${line}`)} limit={8} color={skin.error} tail={false} /><ContentPane title="After" skin={skin} lines={String(replacement.replace ?? "").split(/\r?\n/).map((line) => `+ ${line}`)} limit={8} color={skin.success} tail={false} /></InspectorCard>) : <ContentPane title={action.operation === "create" ? "New content" : "Replacement content"} skin={skin} lines={String(action.content ?? "").split(/\r?\n/)} limit={12} tail={false} />}</InspectorCard>)}</>
}

export function EditView(props) {
  const parsed = createMemo(() => parseEditResult(String(props.output ?? "")))
  const lifecycle = createMemo(() => lifecycleOf(props.part))
  const status = createMemo(() => resolvedStatus(props.part, parsed()?.status))
  const plan = createMemo(() => inputItems("alonix-edit", props.input))
  const planReady = createMemo(() => inputPlanAvailable("alonix-edit", props.input))
  const observed = createMemo(() => parsed() ? [...parsed().applied.map((file) => ({ status: "SUCCESS", label: file.path, meta: operationFor(props.input, file.path, file.kind) })), ...parsed().unchanged.map((file) => ({ status: "SUCCESS", label: file.path, meta: "unchanged" })), ...parsed().rejected.map((file) => ({ status: "FAILED", label: file.path, meta: "rejected" }))] : [])
  const batch = createMemo(() => reconcileBatch(plan(), observed()))
  const items = createMemo(() => batch().records.map((item) => ({ ...item, label: displayPath(item.label, 84) })))
  const total = createMemo(() => batch().plannedCount)
  const summary = createMemo(() => parsed() ? `${total()} transaction${total() === 1 ? "" : "s"} · ${parsed().applied.length} changed${parsed().rejected.length ? ` · ${parsed().rejected.length} rejected` : ""}${batch().omitted.length ? ` · ${batch().omitted.length} details omitted` : ""}` : pendingPlanSummary(planReady(), total(), "transaction"))
  const fileCard = (file, rejected = false, unchanged = false) => <InspectorCard title={displayPath(file.path, 100)} skin={props.skin} status={rejected ? "FAILED" : "SUCCESS"} meta={rejected ? "not changed" : unchanged ? "already satisfied" : operationFor(props.input, file.path, file.kind)} subtitle={rejected ? file.safety : null}><MetaGrid skin={props.skin} entries={rejected ? [["failed step", file.failedStep], ["expected", file.expected], ["observed", file.observed]] : [["actions evaluated", file.actions], ["final size", file.size], ["sha256", file.sha256]]} /><Section title="Intended transaction" skin={props.skin} tight><ContentPane skin={props.skin} lines={intendedActions(props.input, file.path)} tail={false} /><IntendedDetails input={props.input} path={file.path} skin={props.skin} /></Section></InspectorCard>
  const details = () => {
    const result = parsed()
    if (!result) {
      if (statusPending(status())) return <InspectorCard title={planReady() ? "Edit plan" : "Preparing edit"} skin={props.skin} status={status()} pending meta={planReady() ? `${total()} transaction(s)` : "input pending"}>{planReady() ? <PreviewList skin={props.skin} items={items()} limit={12} /> : <text fg={props.skin.muted}>Waiting for OpenCode to attach the validated edit actions.</text>}</InspectorCard>
      if (lifecycle().phase === "error") return <InspectorUnavailable skin={props.skin} message={lifecycle().error} />
      return <InspectorDegraded skin={props.skin} items={items()} message={`The completed edit output was bounded before the EDIT RESULT header. All ${total()} canonical request transactions remain visible; the saved tool output contains the authoritative result.`} />
    }
    return <><OutcomeOverview skin={props.skin} status={result.status} summary={result.outcome} facts={[["requested transactions", total()], ["changed", result.applied.length], ["already satisfied", result.unchanged.length], ["rejected safely", result.rejected.length], ["details omitted", batch().omitted.length]]} meaning={batch().omitted.length ? ["The original canonical transaction plan remains authoritative; bounded output omitted some result blocks.", "Omitted details are uncertainty, not rejection or renderer failure."] : result.rejected.length ? ["Committed files changed successfully; rejected files remained untouched.", "Each canonical transaction has exactly one result row below."] : ["Every canonical file transaction completed or was already satisfied."]} />{result.consistency.length ? <InspectorUnavailable skin={props.skin} message={`The edit report declared counts that did not match parsed rows: ${result.consistency.join("; ")}.`} /> : null}{result.applied.length ? <Section title="Changed" skin={props.skin} meta={`${result.applied.length}`}>{result.applied.map((file) => fileCard(file))}</Section> : null}{result.unchanged.length ? <Section title="Already satisfied" skin={props.skin} meta={`${result.unchanged.length}`}>{result.unchanged.map((file) => fileCard(file, false, true))}</Section> : null}{result.rejected.length ? <Section title="Rejected safely" skin={props.skin} meta={`${result.rejected.length}`} color={props.skin.error}>{result.rejected.map((file) => fileCard(file, true))}</Section> : null}{batch().omitted.length ? <Section title="Requested transactions without visible detail" skin={props.skin} meta={`${batch().omitted.length}`}>{batch().omitted.map((item) => <InspectorDegraded skin={props.skin} title={displayPath(item.label, 100)} />)}</Section> : null}<InspectorCard title="Transaction safety" skin={props.skin} status={result.rejected.length ? "PARTIAL SUCCESS" : "SUCCESS"} subtitle={result.safetyModel}><MetaGrid skin={props.skin} entries={Object.entries(result.technicalSummary)} /></InspectorCard></>
  }
  return <Activity evidence={props.output} label="Edit" summary={summary()} meta={statusLabel(status())} status={status()} pending={statusPending(status())} skin={props.skin} preview={items().length ? <PreviewList skin={props.skin} items={items()} /> : null} openDefault={Boolean(parsed()?.rejected.length || parsed()?.consistency.length)} details={details} />
}
