/** @jsxImportSource @opentui/solid */
import { createMemo } from "solid-js"
import { parseEditResult } from "../lib/edit-many.js"
import { inputItems } from "../lib/inspect.js"
import { Activity, ContentPane, displayPath, InspectorCard, lifecycleOf, MetaGrid, OutcomeOverview, PreviewList, RawEvidence, resolvedStatus, Section, statusLabel } from "./kit.jsx"

function intendedActions(input, path) {
  return (input?.actions ?? []).filter((action) => action.path === path).map((action) => {
    if (action.operation === "patch") return `patch · ${action.replacements?.length ?? 0} exact replacement(s)`
    if (action.operation === "create") return `create · ${String(action.content ?? "").split(/\r?\n/).length} line(s)`
    return `overwrite · ${String(action.content ?? "").split(/\r?\n/).length} line(s)`
  })
}

function IntendedDetails({ input, path, skin }) {
  const actions = (input?.actions ?? []).filter((action) => action.path === path)
  return <>{actions.map((action, actionIndex) => <InspectorCard title={`${action.operation} ${actionIndex + 1}`} skin={skin} status="PENDING" meta={action.operation === "patch" ? `${action.replacements?.length ?? 0} replacements` : `${String(action.content ?? "").split(/\r?\n/).length} lines`} nested>{action.operation === "patch" ? (action.replacements ?? []).slice(0, 6).map((replacement, index) => <InspectorCard title={`Exact replacement ${index + 1}`} skin={skin} status="PARTIAL SUCCESS" meta={`expected ${replacement.expected_count ?? 1}`} nested><ContentPane title="Before" skin={skin} lines={String(replacement.search ?? "").split(/\r?\n/).map((line) => `- ${line}`)} limit={8} color={skin.error} tail={false} /><ContentPane title="After" skin={skin} lines={String(replacement.replace ?? "").split(/\r?\n/).map((line) => `+ ${line}`)} limit={8} color={skin.success} tail={false} /></InspectorCard>) : <ContentPane title={action.operation === "create" ? "New content" : "Replacement content"} skin={skin} lines={String(action.content ?? "").split(/\r?\n/)} limit={12} tail={false} />}</InspectorCard>)}</>
}

export function EditManyView(props) {
  const parsed = createMemo(() => parseEditResult(String(props.output ?? "")))
  const lifecycle = createMemo(() => lifecycleOf(props.part))
  const status = createMemo(() => resolvedStatus(props.part, parsed()?.status))
  const items = createMemo(() => parsed() ? [...parsed().applied.map((file) => ({ status: "SUCCESS", label: displayPath(file.path, 84), meta: file.kind })), ...parsed().unchanged.map((file) => ({ status: "SUCCESS", label: displayPath(file.path, 84), meta: "unchanged" })), ...parsed().rejected.map((file) => ({ status: "FAILED", label: displayPath(file.path, 84), meta: "rejected" }))] : inputItems("alonix-edit-many", props.input))
  const summary = createMemo(() => lifecycle().phase === "completed" ? parsed()?.outcome ?? `Processed ${items().length} files` : `Preparing ${items().length} file transaction${items().length === 1 ? "" : "s"}`)
  const fileCard = (file, rejected = false, unchanged = false) => <InspectorCard title={displayPath(file.path, 100)} skin={props.skin} status={rejected ? "FAILED" : "SUCCESS"} meta={rejected ? "not changed" : unchanged ? "already satisfied" : file.kind} subtitle={rejected ? file.safety : null}><MetaGrid skin={props.skin} entries={rejected ? [["failed step", file.failedStep], ["expected", file.expected], ["observed", file.observed]] : [["actions evaluated", file.actions], ["final size", file.size], ["sha256", file.sha256], ["aliases", file.aliases?.join(", ")]]} /><Section title="Intended transaction" skin={props.skin} tight><ContentPane skin={props.skin} lines={intendedActions(props.input, file.path)} tail={false} /><IntendedDetails input={props.input} path={file.path} skin={props.skin} /></Section>{!rejected && (file.recovery.length || file.noOps.length) ? <ContentPane title="Recovery and no-op evidence" skin={props.skin} lines={[...file.recovery, ...file.noOps]} /> : null}</InspectorCard>
  return <Activity label="edit" summary={summary().slice(0, 130)} meta={statusLabel(status(), lifecycle())} status={status()} pending={lifecycle().pending} skin={props.skin} preview={<PreviewList skin={props.skin} items={items()} />} openDefault={Boolean(parsed()?.rejected.length)} details={() => parsed() ? <><OutcomeOverview skin={props.skin} status={parsed().status} summary={parsed().outcome} facts={[["files changed", parsed().applied.length], ["already satisfied", parsed().unchanged.length], ["rejected safely", parsed().rejected.length]]} meaning={parsed().rejected.length ? ["Committed files changed successfully; rejected files were left untouched.", "Open a rejected file first to see the exact failed step, expected condition, and observed evidence."] : ["Every intended file transaction completed or was already satisfied."]} /><Section title="Committed files" skin={props.skin} meta={`${parsed().applied.length} changed`}>{parsed().applied.map((file) => fileCard(file))}</Section>{parsed().unchanged.length ? <Section title="Already satisfied" skin={props.skin}>{parsed().unchanged.map((file) => fileCard(file, false, true))}</Section> : null}{parsed().rejected.length ? <Section title="Rejected safely" skin={props.skin} color={props.skin.error}>{parsed().rejected.map((file) => fileCard(file, true))}</Section> : null}<InspectorCard title="Transaction safety" skin={props.skin} status={parsed().rejected.length ? "PARTIAL SUCCESS" : "SUCCESS"} subtitle={parsed().safetyModel}><MetaGrid skin={props.skin} entries={Object.entries(parsed().technicalSummary)} />{parsed().readWriteRecovery.length ? <ContentPane title="Read/write recovery" skin={props.skin} lines={parsed().readWriteRecovery} /> : null}</InspectorCard></> : <><Section title="Requested operations" skin={props.skin}>{(props.input?.actions ?? []).map((action) => <InspectorCard title={displayPath(action.path, 100)} skin={props.skin} status="PENDING" meta={action.operation}><IntendedDetails input={props.input} path={action.path} skin={props.skin} /></InspectorCard>)}</Section><RawEvidence skin={props.skin} text={lifecycle().error || props.output} /></>} />
}
