/** @jsxImportSource @opentui/solid */
import { createMemo } from "solid-js"
import { parseReadResult } from "../lib/read-many.js"
import { inputItems } from "../lib/inspect.js"
import { Activity, DetailLines, displayPath, lifecycleOf, MetaGrid, PreviewList, RawEvidence, resolvedStatus, Section, statusLabel } from "./kit.jsx"

export function ReadManyView(props) {
  const parsed = createMemo(() => parseReadResult(String(props.output ?? "")))
  const lifecycle = createMemo(() => lifecycleOf(props.part))
  const status = createMemo(() => resolvedStatus(props.part, parsed()?.status))
  const items = createMemo(() => parsed() ? [...parsed().files.map((file) => ({ status: file.bounded ? "PARTIAL SUCCESS" : "SUCCESS", label: displayPath(file.path, 84), meta: file.bounded ? "bounded" : file.kind })), ...parsed().unavailable.map((item) => ({ status: "FAILED", label: displayPath(item.path, 84), meta: "unavailable" }))] : inputItems("fs_read_many", props.input))
  const summary = createMemo(() => lifecycle().phase === "completed" ? parsed()?.outcome ?? `Read ${items().length} targets` : `Reading ${items().length} target${items().length === 1 ? "" : "s"}`)
  return <Activity label="read" summary={summary().slice(0, 130)} meta={statusLabel(status(), lifecycle())} status={status()} pending={lifecycle().pending} skin={props.skin} preview={<PreviewList skin={props.skin} items={items()} />} details={() => parsed() ? <><Section title="Returned evidence" skin={props.skin} meta={`${parsed().files.length} target(s)`}>{parsed().files.map((file) => <Section title={displayPath(file.path, 100)} skin={props.skin} color={file.bounded ? props.skin.accent : props.skin.success} meta={file.bounded ? "bounded" : file.kind}><MetaGrid skin={props.skin} entries={[["encoding", file.encoding], ["source bytes", file.sourceBytes], ["returned bytes", file.returnedRenderedBytes], ["ranges", file.ranges], ["sha256", file.sha256]]} /></Section>)}</Section>{parsed().unavailable.length ? <Section title="Unavailable" skin={props.skin} color={props.skin.error}><DetailLines skin={props.skin} lines={parsed().unavailable.map((item) => `${item.path} — ${item.reason}`)} /></Section> : null}{parsed().omitted.length ? <Section title="Bounded evidence" skin={props.skin}><DetailLines skin={props.skin} lines={parsed().omitted.map((item) => item.note || `${item.path} · omitted lines ${item.lines} · ${item.bytes} bytes`)} /></Section> : null}<Section title="Budget and recovery" skin={props.skin}><MetaGrid skin={props.skin} entries={[...Object.entries(parsed().budget), ...Object.entries(parsed().editContext)]} /><DetailLines skin={props.skin} lines={[...parsed().consolidation, ...parsed().recovery, ...parsed().possiblePaths]} /></Section></> : <RawEvidence skin={props.skin} text={lifecycle().error || props.output} />} />
}
