/** @jsxImportSource @opentui/solid */
import { createMemo } from "solid-js"
import { parseReadResult } from "../lib/read-many.js"
import { inputItems } from "../lib/inspect.js"
import { Activity, ContentPane, displayPath, InspectorCard, lifecycleOf, MetaGrid, PreviewList, RawEvidence, resolvedStatus, Section, statusLabel } from "./kit.jsx"

export function ReadManyView(props) {
  const parsed = createMemo(() => parseReadResult(String(props.output ?? "")))
  const lifecycle = createMemo(() => lifecycleOf(props.part))
  const status = createMemo(() => resolvedStatus(props.part, parsed()?.status))
  const items = createMemo(() => parsed() ? [...parsed().files.map((file) => ({ status: file.bounded ? "PARTIAL SUCCESS" : "SUCCESS", label: displayPath(file.path, 84), meta: file.bounded ? "bounded" : file.kind })), ...parsed().unavailable.map((item) => ({ status: "FAILED", label: displayPath(item.path, 84), meta: "unavailable" }))] : inputItems("fs_read_many", props.input))
  const summary = createMemo(() => lifecycle().phase === "completed" ? parsed()?.outcome ?? `Read ${items().length} targets` : `Reading ${items().length} target${items().length === 1 ? "" : "s"}`)
  return <Activity label="read" summary={summary().slice(0, 130)} meta={statusLabel(status(), lifecycle())} status={status()} pending={lifecycle().pending} skin={props.skin} preview={<PreviewList skin={props.skin} items={items()} />} details={() => parsed() ? <><Section title="Returned evidence" skin={props.skin} meta={`${parsed().files.length} target(s)`}>{parsed().files.map((file) => <InspectorCard title={displayPath(file.path, 100)} skin={props.skin} status={file.bounded ? "PARTIAL SUCCESS" : "SUCCESS"} meta={file.bounded ? "bounded evidence" : file.kind}><MetaGrid skin={props.skin} entries={[["encoding", file.encoding], ["source bytes", file.sourceBytes], ["returned bytes", file.returnedRenderedBytes], ["ranges", file.ranges], ["sha256", file.sha256]]} /></InspectorCard>)}</Section>{parsed().unavailable.map((item) => <InspectorCard title={displayPath(item.path, 100)} skin={props.skin} status="FAILED" meta="unavailable" subtitle={item.reason}>{parsed().possiblePaths.length ? <ContentPane title="Possible paths" skin={props.skin} lines={parsed().possiblePaths.filter((line) => line.startsWith(item.path))} limit={8} tail={false} /> : null}</InspectorCard>)}{parsed().omitted.length ? <Section title="Bounded evidence" skin={props.skin}>{parsed().omitted.map((item) => <InspectorCard title={displayPath(item.path, 100)} skin={props.skin} status="PARTIAL SUCCESS" meta={item.bytes ? `${item.bytes} bytes omitted` : "bounded"} subtitle={item.note || `Omitted lines ${item.lines}`} />)}</Section> : null}<InspectorCard title="Budget and recovery" skin={props.skin} status={parsed().recovery.length ? "PARTIAL SUCCESS" : "SUCCESS"}><MetaGrid skin={props.skin} entries={[...Object.entries(parsed().budget), ...Object.entries(parsed().editContext)]} />{parsed().consolidation.length || parsed().recovery.length ? <ContentPane title="Recovery signals" skin={props.skin} lines={[...parsed().consolidation, ...parsed().recovery]} limit={16} /> : null}</InspectorCard></> : <RawEvidence skin={props.skin} text={lifecycle().error || props.output} />} />
}
