/** @jsxImportSource @opentui/solid */
import { createMemo } from "solid-js"
import { parseShellCommands } from "../lib/shell.js"
import { inputItems } from "../lib/inspect.js"
import { Activity, ContentPane, displayPath, InspectorCard, InspectorUnavailable, lifecycleOf, MetaGrid, OutcomeOverview, PreviewList, resolvedStatus, Section, statusLabel, statusPending } from "./kit.jsx"
function commandStatus(command) { return command.exit === 0 ? "SUCCESS" : command.exit == null ? "PARTIAL SUCCESS" : "FAILED" }
export function ShellView(props) {
  const text = createMemo(() => String(props.output ?? "").trim())
  const lifecycle = createMemo(() => lifecycleOf(props.part))
  const commands = createMemo(() => parseShellCommands(text()))
  const resultStatus = createMemo(() => text().match(/^TERMINAL RESULT: (SUCCESS|PARTIAL SUCCESS|FAILED)$/m)?.[1] ?? null)
  const status = createMemo(() => resolvedStatus(props.part, resultStatus()))
  const items = createMemo(() => commands().length ? commands().map((command) => ({ status: commandStatus(command), label: displayPath(command.label || command.command, 84), meta: command.duration || (command.exit == null ? "incomplete" : `exit ${command.exit}`) })) : inputItems("alonix-shell", props.input))
  const summary = createMemo(() => resultStatus() ? `${commands().filter((item) => item.exit === 0).length}/${commands().length} commands succeeded` : `${items().length} command${items().length === 1 ? "" : "s"}`)
  const details = () => commands().length ? <><OutcomeOverview skin={props.skin} status={resultStatus() ?? "PARTIAL SUCCESS"} summary={text().match(/^WHAT HAPPENED: (.+)$/m)?.[1] ?? summary()} facts={[["commands", commands().length], ["succeeded", commands().filter((item) => item.exit === 0).length], ["failed or interrupted", commands().filter((item) => item.exit !== 0).length]]} meaning={resultStatus() === "SUCCESS" ? ["Every command completed successfully."] : ["Review the failed command first; later sequential commands may not have run."]} /><Section title="Command results" skin={props.skin}>{commands().map((command) => <InspectorCard title={`${command.num}. ${command.label || "Unlabelled command"}`} skin={props.skin} status={commandStatus(command)} meta={command.duration || `exit ${command.exit ?? "?"}`} subtitle={command.meaning}>{command.body.length ? <ContentPane title="Output" skin={props.skin} lines={command.body} limit={24} /> : <ContentPane title="Output" skin={props.skin} lines={["No output was captured."]} tail={false} />}<MetaGrid skin={props.skin} entries={[["exit", command.exit ?? "not completed"], ["command", command.command], ["directory", command.workdir]]} />{command.technical.length ? <ContentPane title="Diagnostics" skin={props.skin} lines={command.technical} limit={10} /> : null}</InspectorCard>)}</Section></> : statusPending(status()) ? <InspectorCard title="Command plan" skin={props.skin} status={status()} pending meta={`${items().length} command(s)`}><PreviewList skin={props.skin} items={items()} limit={12} /></InspectorCard> : <InspectorUnavailable skin={props.skin} message={lifecycle().error || "The completed terminal response did not match the command-result contract."} />
  return <Activity label="Shell" summary={summary()} meta={statusLabel(status())} status={status()} pending={statusPending(status())} skin={props.skin} preview={<PreviewList skin={props.skin} items={items()} />} details={details} />
}
