/** @jsxImportSource @opentui/solid */
import { createMemo } from "solid-js"
import { inputItems, parseStealth } from "../lib/inspect.js"
import { Activity, ContentPane, InspectorCard, InspectorUnavailable, lifecycleOf, MetaGrid, OutcomeOverview, PreviewList, resolvedStatus, Section, statusLabel, statusPending } from "./kit.jsx"
function statusResult(text, tool) {
  if (!text) return null
  if (tool === "alonix-stealth-status") { const ready = /^STEALTH STATUS: READY$/m.test(text); return { status: ready ? "SUCCESS" : "PARTIAL SUCCESS", summary: ready ? "Tor boundary ready" : "Tor boundary not ready", lines: String(text).split(/\r?\n/).filter(Boolean) } }
  if (tool === "alonix-stealth-rotate-tor") { const value = text.match(/^STEALTH TOR ROTATION: (SUCCESS|PARTIAL SUCCESS|FAILED)$/m)?.[1]; return { status: value ?? (/FAILED|Error/i.test(text) ? "FAILED" : "PARTIAL SUCCESS"), summary: value === "SUCCESS" ? "Circuit rotated" : value === "FAILED" ? "Rotation failed" : "Partial rotation result", lines: String(text).split(/\r?\n/).filter(Boolean) } }
  return null
}
function labelFor(tool) { if (tool === "alonix-stealth-fetch-many") return "Stealth fetch"; if (tool === "alonix-stealth-search-many") return "Stealth search"; if (tool === "alonix-stealth-rotate-tor") return "Tor rotate"; return "Stealth status" }
export function StealthView(props) {
  const parsed = createMemo(() => parseStealth(props.output ?? ""))
  const simple = createMemo(() => statusResult(props.output ?? "", props.tool))
  const lifecycle = createMemo(() => lifecycleOf(props.part))
  const resultStatus = createMemo(() => parsed()?.status ?? simple()?.status ?? null)
  const status = createMemo(() => resolvedStatus(props.part, resultStatus()))
  const items = createMemo(() => parsed()?.items?.map((item) => ({ status: item.status, label: item.titleText || item.title, meta: item.http || item.outcome })) ?? inputItems(props.tool, props.input))
  const summary = createMemo(() => parsed() ? `${parsed().items.filter((item) => item.status === "SUCCESS").length}/${parsed().items.length} items succeeded` : simple()?.summary ?? `${items().length} item${items().length === 1 ? "" : "s"}`)
  const details = () => parsed() ? <><OutcomeOverview skin={props.skin} status={parsed().status} summary={parsed().summary} facts={[["items", parsed().items.length], ["successful", parsed().items.filter((item) => item.status === "SUCCESS").length], ["failed", parsed().items.filter((item) => item.status === "FAILED").length], ["mode", parsed().kind]]} meaning={["Tor/privacy readiness is separate from each page or query outcome."]} /><InspectorCard title="Privacy boundary" skin={props.skin} status={parsed().status} meta="Tor"><text fg={props.skin.text}>{parsed().tor}</text></InspectorCard><Section title="Item results" skin={props.skin}>{parsed().items.map((item) => <InspectorCard title={`${item.number}. ${item.titleText || item.title}`} skin={props.skin} status={item.status} meta={item.http || item.outcome} subtitle={item.status === "FAILED" ? item.error : item.finalUrl}>{item.content ? <ContentPane title="Returned evidence" skin={props.skin} lines={item.content.split(/\r?\n/)} limit={18} tail={false} /> : null}<MetaGrid skin={props.skin} entries={[["outcome", item.outcome], ["completeness", item.completeness], ["error", item.error]]} /></InspectorCard>)}</Section></> : simple() ? <><OutcomeOverview skin={props.skin} status={simple().status} summary={simple().summary} meaning={[props.tool === "alonix-stealth-status" ? "This checks readiness only; it does not fetch a page." : "The managed Tor boundary returned this rotation outcome."]} /><ContentPane title="Boundary details" skin={props.skin} lines={simple().lines} limit={12} tail={false} /></> : statusPending(status()) ? <InspectorCard title={`${labelFor(props.tool)} plan`} skin={props.skin} status={status()} pending>{items().length ? <PreviewList skin={props.skin} items={items()} limit={12} /> : <text fg={props.skin.muted}>Waiting for managed Tor boundary response.</text>}</InspectorCard> : <InspectorUnavailable skin={props.skin} message={lifecycle().error || `The completed ${props.tool} response did not match its stealth report contract.`} />
  return <Activity label={labelFor(props.tool)} summary={summary()} meta={statusLabel(status())} status={status()} pending={statusPending(status())} skin={props.skin} preview={items().length ? <PreviewList skin={props.skin} items={items()} /> : null} details={details} />
}
