/** @jsxImportSource @opentui/solid */
import { createMemo } from "solid-js"
import { inputItems, parseWebFetch, parseWebSearch } from "../lib/inspect.js"
import { Activity, ContentPane, InspectorCard, InspectorUnavailable, lifecycleOf, MetaGrid, OutcomeOverview, PreviewList, resolvedStatus, Section, statusLabel, statusPending } from "./kit.jsx"
function FetchDetails(props) { return <Section title="URL results" skin={props.skin}>{props.items.map((item) => <InspectorCard title={`${item.number}. ${item.titleText || item.title}`} skin={props.skin} status={item.status} meta={item.outcome} subtitle={item.status === "FAILED" ? item.error || "No content returned." : item.finalUrl}>{item.extracted ? <ContentPane title="Extracted content" skin={props.skin} lines={item.extracted.split(/\r?\n/)} limit={20} tail={false} /> : <ContentPane title="Extracted content" skin={props.skin} lines={[item.error || "No extracted content was returned."]} tail={false} color={item.status === "FAILED" ? props.skin.error : props.skin.muted} />}<MetaGrid skin={props.skin} entries={[["final URL", item.finalUrl], ["completeness", item.completeness], ["cache", item.cache], ["duration", item.duration]]} /></InspectorCard>)}</Section> }
function SearchDetails(props) { return <Section title="Query results" skin={props.skin}>{props.items.map((item) => <InspectorCard title={`${item.number}. ${item.title}`} skin={props.skin} status={item.status} meta={item.outcome} subtitle={item.results.length ? `${item.results.length} result(s)` : "No usable result returned."}>{item.results.slice(0, 8).map((result, index) => <InspectorCard title={`${index + 1}. ${result.title}`} skin={props.skin} status="SUCCESS" meta={result.source} subtitle={result.url} nested><text fg={props.skin.text}>{result.snippet}</text></InspectorCard>)}<MetaGrid skin={props.skin} entries={[["cache", item.cache], ["backend attempts", item.attempts.join(" · ")]]} /></InspectorCard>)}</Section> }
export function WebView(props) {
  const isFetch = createMemo(() => props.tool === "alonix-web-fetch-many")
  const parsed = createMemo(() => isFetch() ? parseWebFetch(props.output ?? "") : parseWebSearch(props.output ?? ""))
  const lifecycle = createMemo(() => lifecycleOf(props.part))
  const status = createMemo(() => resolvedStatus(props.part, parsed()?.status))
  const items = createMemo(() => parsed()?.items?.map((item) => ({ status: item.status, label: item.titleText || item.title, meta: item.outcome || item.http })) ?? inputItems(props.tool, props.input))
  const label = createMemo(() => isFetch() ? "Web fetch" : "Web search")
  const summary = createMemo(() => parsed() ? `${parsed().items.filter((item) => item.status === "SUCCESS").length}/${parsed().items.length} ${isFetch() ? "URLs" : "queries"} succeeded` : `${items().length} ${isFetch() ? "URL" : "quer"}${items().length === 1 ? (isFetch() ? "" : "y") : (isFetch() ? "s" : "ies")}`)
  const details = () => parsed() ? <><OutcomeOverview skin={props.skin} status={parsed().status} summary={parsed().summary} facts={[[isFetch() ? "URLs" : "queries", parsed().items.length], ["successful", parsed().items.filter((item) => item.status === "SUCCESS").length], ["partial or failed", parsed().items.filter((item) => item.status !== "SUCCESS").length], ["allocation", parsed().allocation]]} meaning={parsed().status === "SUCCESS" ? ["Every requested item returned usable evidence."] : ["Each item below has its own outcome; do not apply the overall status to every URL or query."]} />{isFetch() ? <FetchDetails skin={props.skin} items={parsed().items} /> : <SearchDetails skin={props.skin} items={parsed().items} />}</> : statusPending(status()) ? <InspectorCard title={`${label()} plan`} skin={props.skin} status={status()} pending meta={`${items().length} item(s)`}><PreviewList skin={props.skin} items={items()} limit={12} /></InspectorCard> : <InspectorUnavailable skin={props.skin} message={lifecycle().error || `The completed ${props.tool} response did not match its per-item report contract.`} />
  return <Activity label={label()} summary={summary()} meta={statusLabel(status())} status={status()} pending={statusPending(status())} skin={props.skin} preview={<PreviewList skin={props.skin} items={items()} />} details={details} />
}
