import { createHash, randomBytes } from "node:crypto";
import { closeSync, existsSync, mkdirSync, openSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createConnection } from "node:net";
import { delimiter, resolve } from "node:path";
import { spawn, spawnSync } from "node:child_process";
import { root } from "./paths.mjs";

const serviceRoot = resolve(root, "services", "searxng");
const runtimeRoot = resolve(serviceRoot, ".runtime");
const statePath = resolve(runtimeRoot, "service.json");
const settingsPath = resolve(serviceRoot, "settings.local.yml");
const port = 18999;

export function searxPython() { return process.platform === "win32" ? resolve(serviceRoot, ".venv", "Scripts", "python.exe") : resolve(serviceRoot, ".venv", "bin", "python"); }
export function pidAlive(pid) { if (!Number.isInteger(pid) || pid <= 0) return false; try { process.kill(pid, 0); return true; } catch { return false; } }
function commandLine(pid) { if (process.platform !== "win32") return ""; const script = `(Get-CimInstance Win32_Process -Filter \"ProcessId=${pid}\").CommandLine`; const result = spawnSync("powershell.exe", ["-NoProfile", "-NonInteractive", "-Command", script], { encoding: "utf8", timeout: 5000, windowsHide: true }); return result.status === 0 ? result.stdout.trim() : ""; }
function listenerPid(targetPort = port) { if (process.platform !== "win32") return null; const script = `$c=Get-NetTCPConnection -State Listen -LocalPort ${targetPort} -ErrorAction SilentlyContinue | Select-Object -First 1; if($c){$c.OwningProcess}`; const result = spawnSync("powershell.exe", ["-NoProfile", "-NonInteractive", "-Command", script], { encoding: "utf8", timeout: 5000, windowsHide: true }); const pid = Number(result.stdout.trim()); return Number.isInteger(pid) && pid > 0 ? pid : null; }
function owned(state) { if (!state || !pidAlive(state.pid)) return false; if (state.root_hash !== createHash("sha256").update(serviceRoot.toLowerCase()).digest("hex")) return false; if (process.platform === "win32") { const line = commandLine(state.pid).toLowerCase(); return line.includes(resolve(serviceRoot, "run_local.py").toLowerCase()); } return true; }
function readState() { try { return JSON.parse(readFileSync(statePath, "utf8")); } catch { return null; } }
function portOpen(targetPort = port) { return new Promise((resolvePromise) => { const socket = createConnection({ host: "127.0.0.1", port: targetPort }); const done = (value) => { socket.destroy(); resolvePromise(value); }; socket.setTimeout(500); socket.once("connect", () => done(true)); socket.once("timeout", () => done(false)); socket.once("error", () => done(false)); }); }
export function ensureSearxSettings() { mkdirSync(runtimeRoot, { recursive: true }); if (!existsSync(settingsPath)) { const secret = randomBytes(32).toString("hex"); writeFileSync(settingsPath, `use_default_settings: true\n\ngeneral:\n  debug: false\n  instance_name: \"SearXNG Local (OpenCode Optimised Toolings)\"\n\nsearch:\n  safe_search: 0\n  autocomplete: \"\"\n  formats:\n    - html\n    - json\n\nserver:\n  port: ${port}\n  bind_address: \"127.0.0.1\"\n  secret_key: \"${secret}\"\n  limiter: false\n  public_instance: false\n  image_proxy: false\n\nui:\n  static_use_hash: true\n`, { encoding: "utf8", mode: 0o600 }); } return settingsPath; }
export async function statusSearx() { const state = readState(); const isOwned = owned(state); const listening = await portOpen(); return { service: "searxng", status: isOwned && listening ? "running" : listening ? "occupied-unowned" : isOwned ? "starting" : "stopped", pid: isOwned ? state.pid : null, port, settings: settingsPath, python: searxPython(), installed: existsSync(searxPython()) }; }
export async function startSearx() { const status = await statusSearx(); if (status.status === "running") return status; if (status.status === "occupied-unowned") throw new Error(`Port ${port} is occupied by a process not owned by this distribution.`); if (!existsSync(searxPython())) throw new Error("SearXNG Python environment is missing. Run `npm run setup` first."); ensureSearxSettings(); mkdirSync(runtimeRoot, { recursive: true }); const logPath = resolve(runtimeRoot, "service.log"); const log = openSync(logPath, "w"); const child = spawn(searxPython(), [resolve(serviceRoot, "run_local.py")], { cwd: serviceRoot, detached: process.platform !== "win32", windowsHide: true, stdio: ["ignore", log, log], env: { ...process.env, SEARXNG_SETTINGS_PATH: settingsPath } }); closeSync(log); child.unref(); const state = { pid: child.pid, root_hash: createHash("sha256").update(serviceRoot.toLowerCase()).digest("hex"), started_at: new Date().toISOString(), log: logPath }; writeFileSync(statePath, JSON.stringify(state, null, 2), { encoding: "utf8", mode: 0o600 }); const deadline = Date.now() + 30_000; while (Date.now() < deadline) { if (!pidAlive(child.pid)) { let detail = ""; try { detail = readFileSync(logPath, "utf8").slice(-4000); } catch {} throw new Error(`SearXNG exited before becoming ready.${detail ? `\n${detail}` : ""}`); } if (await portOpen()) { const actualPid = listenerPid() || child.pid; const line = process.platform === "win32" ? commandLine(actualPid).toLowerCase() : ""; if (process.platform === "win32" && !line.includes(resolve(serviceRoot, "run_local.py").toLowerCase())) throw new Error(`Port ${port} became occupied by an unverifiable process; refusing ownership.`); state.pid = actualPid; writeFileSync(statePath, JSON.stringify(state, null, 2), { encoding: "utf8", mode: 0o600 }); return statusSearx(); } await new Promise((resolvePromise) => setTimeout(resolvePromise, 500)); } throw new Error("SearXNG did not become ready within 30 seconds."); }
export async function stopSearx() { const state = readState(); if (!state) return statusSearx(); if (!owned(state)) { rmSync(statePath, { force: true }); if (await portOpen()) throw new Error("SearXNG state was stale and the port is owned by an unrelated process; nothing was terminated."); return statusSearx(); } process.kill(state.pid, "SIGTERM"); let deadline = Date.now() + 8000; while (Date.now() < deadline && (pidAlive(state.pid) || await portOpen())) await new Promise((resolvePromise) => setTimeout(resolvePromise, 200)); if (pidAlive(state.pid)) process.kill(state.pid, "SIGKILL"); deadline = Date.now() + 4000; while (Date.now() < deadline && await portOpen()) await new Promise((resolvePromise) => setTimeout(resolvePromise, 200)); if (await portOpen()) throw new Error(`Verified SearXNG process ${state.pid} was terminated but port ${port} did not close; state retained for diagnosis.`); rmSync(statePath, { force: true }); return statusSearx(); }
